name: Subtitles
options:
  bundleIdPrefix: br.com.subtitles
targets:
  Framework:
      name: AVPlayerItemSubtitles
      type: framework
      platform: iOS
      deploymentTarget: "13.0"
      sources: [Sources]
  Application:
    name: Sample
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Sample]
    dependencies:
      - target: AVPlayerItemSubtitles
  Unit:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Tests]
    dependencies:
      - target: AVPlayerItemSubtitles
  